# Generated by Django 5.0 on 2024-01-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_blog_content_alter_blog_slug_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='is_active',
        ),
        migrations.AddField(
            model_name='version',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='Признак текущей версии'),
        ),
        migrations.AlterField(
            model_name='version',
            name='No_version',
            field=models.CharField(max_length=50, unique=True, verbose_name='Номер версии'),
        ),
        migrations.AlterField(
            model_name='version',
            name='name_version',
            field=models.CharField(max_length=100, verbose_name='Название версии'),
        ),
    ]
